[versions]
android-compileSdk = "36"
android-minSdk = "23"
android-targetSdk = "36"
activity-compose-version = "1.11.0"
kotlin-version = "2.3.0-Beta2"
ksp-version = "2.3.0"
androidx-test-ext-junit-version = "1.3.0"
androidx-test-runner-version = "1.7.0"
mockk-version = "1.14.6"
android-gradle-plugin-version = "8.13.0"
compose-version = "1.7.1"
compose-plugin-version = "1.10.0-alpha03"
ktor-version = "3.3.1"
coroutines-version = "1.10.2"
serialization-version = "1.9.0"
sl4j-version = "1.7.36"
lifecycle-compose-version = "2.10.0-alpha03"
coil-version = "3.3.0"
navigation-compose-version = "2.9.1"

material-version = "1.2.0"
appcompat-version = "1.2.0"
recyclerview-version = "1.1.0"
cardview-version = "1.0.0"
constraintlayout-version = "2.0.0"
retrofit-version = "2.9.0"
okhttp-version = "4.8.1"
moshi-version = "1.9.3"
glide-version = "4.16.0"
dagger-version = "2.52"
javax-inject-version = "1"
junit-version = "4.12"
espresso-version = "3.1.0"
test-rules-version = "1.1.0"
hamcrest-version = "1.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin-version" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin-version" }
com-google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin-version" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose-version" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit-version" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner-version" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin-version" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk-version" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk-version" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk-version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-client-content-negotation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor-version" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-version" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-version" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines-version" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-version" }
jetbrains-androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-compose-version" }
sl4j-android = { module = "org.slf4j:slf4j-android", version.ref = "sl4j-version" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil-version" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil-version" }
jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose-version" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi-version" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-version" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-version" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit-version" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-version" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject-version" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat-version" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview-version" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview-version" }
material = { module = "com.google.android.material:material", version.ref = "material-version" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout-version" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide-version" }
glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glide-version" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger-version" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-version" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger-version" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger-version" }
dagger-android-compiler = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger-version" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-version" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-version" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-version" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose-version" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-version" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-version" }
junit = { module = "junit:junit", version.ref = "junit-version" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-version" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso-version" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso-version" }
android-rules = { module = "androidx.test:rules", version.ref = "test-rules-version" }
hamcrest = { module = "org.hamcrest:hamcrest-all", version.ref = "hamcrest-version" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-version" }
